(deftheme liteblu
  "Liteblu theme")

(custom-theme-set-faces
 'liteblu
 '(cursor ((t (:background "black"))))
 '(highlight-numbers-number ((t (:foreground "dark green"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#008ED1"))))
 '(homoglyph ((t (:weight bold :foreground "#008ED1"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "black" :background "gold"))))
 '(highlight ((t (:underline nil :foreground "#2e3436" :background "#FFF876"))))
 '(region ((t (:extend t :foreground "#f6f3e8" :background "#ABDFFA"))))
 '(shadow ((t (:foreground "#7F7F7F"))))
 '(secondary-selection ((t (:weight bold :extend t :foreground "#f6f3e8" :background "#FBE448"))))
 '(trailing-whitespace ((t (:background "#FFFF57"))))
 '(font-lock-builtin-face ((t (:foreground "#006FE0"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#066555"))))
 '(font-lock-comment-face ((t (:foreground "#066555"))))
 '(font-lock-constant-face ((t (:foreground "#D0372D"))))
 '(font-lock-doc-face ((t (:foreground "#036A07"))))
 '(font-lock-function-name-face ((t (:foreground "#74531f" :weight normal))))
 '(font-lock-keyword-face ((t (:foreground "#0000FF" :weight normal))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#8a1bff"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :inherit nil))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :inherit nil))))
 '(font-lock-string-face ((t (:foreground "#777777"))))
 '(font-lock-type-face ((t (:foreground "#0000FF" :weight normal))))
 '(font-lock-variable-name-face ((t (:foreground "#1f377f" :weight normal))))
 '(font-lock-warning-face ((t (:weight bold :foreground "red"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#006DAF" :background "#333333"))))
 '(link ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#006DAF"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#E5786D"))))
 '(fringe ((t (:foreground "#9B9B9B" :background "#EDEDED"))))
 '(header-line ((t (:weight bold :underline (:color "black" :style line) :overline "black" :foreground "black" :background "#FFFF88"))))
 '(tooltip ((t (:foreground "black" :background "light yellow"))))
 '(mode-line ((t (:foreground "black" :box nil))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "white"))))
 '(mode-line-emphasis ((t (:weight bold :foreground "white"))))
 '(mode-line-highlight ((t (:foreground "yellow"))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#4E4E4C" :style nil) :foreground "#F0F0EF" :background "#9B9C97"))))
 '(isearch ((t (:weight bold :underline (:color "#FF9632" :style line) :background "#FDBD33"))))
 '(isearch-fail ((t (:weight bold :foreground "black" :background "#FF9999"))))
 '(lazy-highlight ((t (:underline (:color "#FF9632" :style line) :foreground "#a0a8b0" :background "#FFFF00"))))
 '(match ((t (:weight bold :background "#FBE448"))))
 '(next-error ((t (:underline nil :background "#FFF876"))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#FFFFFF" :foreground "#333333" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 97 :width normal :foundry "MS  " :family "Consolas")))))

(provide-theme 'liteblu)
