(deftheme yaysayer
  "Created 2021-08-22.")

(custom-theme-set-faces
 'yaysayer
 '(default ((t (:family "Consolas" :foundry "MS  " :width normal :height 97 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#b8baa6" :background "#062625" :stipple nil :inherit nil))))
 '(cursor ((((background light)) (:background "black")) (((background dark)) (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#008ED1"))))
 '(homoglyph ((t (:weight bold :foreground "#008ED1"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#F0DFAF" :background "black"))))
 '(highlight ((t (:underline nil :foreground "#2e3436" :background "#FFF876"))))
 '(region ((t (:extend t :foreground "#beb79f" :background "#0000ff"))))
 '(shadow ((t (:foreground "#7F7F7F"))))
 '(secondary-selection ((t (:weight bold :extend t :foreground "#f6f3e8" :background "#FBE448"))))
 '(trailing-whitespace ((t (:background "#FFFF57"))))
 '(font-lock-builtin-face ((t (:foreground "#006FE0"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#61d05e"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#61d05e"))))
 '(font-lock-constant-face ((t (:foreground "#7debcc"))))
 '(font-lock-doc-face ((t (:foreground "#036A07"))))
 '(font-lock-function-name-face ((t (:weight normal :foreground "#c1d5dc"))))
 '(font-lock-keyword-face ((t (:weight semi-bold :foreground "#bdd3e1"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#a5f4b0"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :inherit nil))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :inherit nil))))
 '(font-lock-string-face ((t (:foreground "#777777"))))
 '(font-lock-type-face ((t (:weight normal :foreground "#a5f4b0"))))
 '(font-lock-variable-name-face ((t (:weight normal :foreground "#c1d6e1"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "red"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#006DAF" :background "#333333"))))
 '(link ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#006DAF"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#E5786D"))))
 '(fringe ((t (:foreground "#9B9B9B" :background "#EDEDED"))))
 '(header-line ((t (:weight bold :underline (:color "black" :style line) :overline "black" :foreground "black" :background "#FFFF88"))))
 '(tooltip ((t (:foreground "black" :background "light yellow"))))
 '(mode-line ((t (:box nil :foreground "#333333" :background "#cccccc"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#333333"))))
 '(mode-line-emphasis ((t (:weight bold :foreground "#333333"))))
 '(mode-line-highlight ((t (:foreground "yellow"))))
 '(mode-line-inactive ((t (:box (:line-width 1 :color "#444444" :style nil) :foreground "#444444" :background "#bbbbbb"))))
 '(isearch ((t (:weight bold :underline (:color "#FF9632" :style line) :background "#FDBD33"))))
 '(isearch-fail ((t (:weight bold :foreground "black" :background "#FF9999"))))
 '(lazy-highlight ((t (:underline (:color "#FF9632" :style line) :foreground "#a0a8b0" :background "#FFFF00"))))
 '(match ((t (:weight bold :background "#FBE448"))))
 '(next-error ((t (:underline nil :background "#FFF876"))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'yaysayer)
